### ISSUE TITLE
Demo does not work at all Oops! An Error Occurred

### ISSUE THREAD

**Issue by softwarelimits** [javiereguiluz/easy-admin-demo#69]
Experienced user will not need a demo - is this agreeable? 

So you should expect newbies to try this - and get frustrated hitting several walls.

I tried to understand why there is no `app/app/config/parameters.yml` and found 
`config/packages/easy_admin.yaml` - however after following the instructions and visiting `127.0.0.1:8000/admin` I get an error:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 
```

The dev webserver logs this: 
```
[Sun Dec 23 21:03:21 2018] 127.0.0.1:56598 [500]: / - Uncaught Symfony\Component\Config\Definition\Exception\InvalidTypeException: The configured class "AppBundle\Entity\Category" for the path "easy_admin.entities.Category2" does not exist. Did you forget to create the entity class or to define its namespace? in /path/to/symfony/easy-admin-demo/vendor/javiereguiluz/easyadmin-bundle/src/Configuration/MetadataConfigPass.php:40
Stack trace:
#0 /path/to/symfony/easy-admin-demo/vendor/javiereguiluz/easyadmin-bundle/src/Configuration/ConfigManager.php(204): EasyCorp\Bundle\EasyAdminBundle\Configuration\MetadataConfigPass->process(Array)
#1 /path/to/symfony/easy-admin-demo/vendor/javiereguiluz/easyadmin-bundle/src/Configuration/ConfigManager.php(187): EasyCorp\Bundle\EasyAdminBundle\Configuration\ConfigManager->doProcessConfig(Array)
#2 /path/to/symfony/easy-admin-demo/vendor/javiereguiluz/easyadmin-bundle/src/Configuration/ConfigManager.php(67): EasyCorp\Bundle\EasyAdminBundle\Configuration\ConfigManager->processConfig()
#3 /path/to/symfo in //path/to/symfony/easy-admin-demo/vendor/javiereguiluz/easyadmin-bundle/src/Configuration/MetadataConfigPass.php on line 40
[Sun Dec 23 21:03:23 2018] 127.0.0.1:56600 [301]: /
[Sun Dec 23 21:03:23 2018] 127.0.0.1:56602 [500]: /admin/
[Sun Dec 23 21:03:31 2018] 127.0.0.1:56604 [500]: /admin/
[Sun Dec 23 21:03:33 2018] 127.0.0.1:56606 [500]: /admin/
[Sun Dec 23 21:03:34 2018] 127.0.0.1:56608 [500]: /admin/
[Sun Dec 23 21:30:03 2018] 127.0.0.1:56814 [500]: /admin/
```
The line that starts with `#3` is no copy-paste error - the first path just ends with `symfo`.

**Comment by bhtomming** [comment]
应该是没有app目录的吧？

**Comment by extragornax** [comment]
app/config/parameters.yml
A blank template would be appreciated since it's in the .gitignore
